BASIC:
  SEED: 26
  BACKUP_CODES: True
  BACKUP_LIST: ['lib', 'tools_cam', 'configs']
  NUM_WORKERS: 8

MODEL:
  ARCH: deit_tscam_base_patch16_224
  CAM_THR: 0.12
  TOP_K: 1

DATA:
  DATASET: ImageNet
  DATADIR: data/ImageNet_ILSVRC2012
  NUM_CLASSES: 1000
  RESIZE_SIZE : 256
  CROP_SIZE : 224
  IMAGE_MEAN : [0.485, 0.456, 0.406]
  IMAGE_STD : [0.229, 0.224, 0.225]

TRAIN:
  BATCH_SIZE: 256

TEST:
  BATCH_SIZE: 256
  SAVE_BOXED_IMAGE: False

SOLVER:
  START_LR: 0.004
  LR_STEPS: [10,12]
  NUM_EPOCHS: 20
  LR_FACTOR: 0.1
  MUMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True
